version: "2"
services:
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/vhost:/etc/nginx/conf.d
      - ./www:/www/
    depends_on:
      - php
    restart : always

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./services/php.dockerfile
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./www:/www/:cached
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8.0.20
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=website
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./config/mysql:/etc/mysql
      - ./database/mysql-data:/var/lib/mysql
      - ./database/mysql-initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always

  redis_server:
    container_name: redis
    image: redis:5.0.7-alpine
